# Generated by Django 5.0.4 on 2024-05-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='MyModel',
        ),
        migrations.RenameField(
            model_name='mymodel',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='mymodel',
            old_name='title',
            new_name='name',
        ),
    ]
